import { jsPDF } from 'jspdf';
import { HistorySession, SessionState } from './types';

export const getDateKey = (date = new Date()) => {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
};

export const formatDuration = (ms: number) => {
  if (ms < 0) ms = 0;
  const totalMins = Math.floor(ms / 60000);
  const hours = Math.floor(totalMins / 60);
  const mins = totalMins % 60;
  return `${hours}h ${mins}m`;
};

export const formatClock = (date: Date) => {
  return date.toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
};

export const formatDate = (date: Date) => {
  return date.toLocaleDateString('en-US', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
};

export const formatTimeShort = (ms: number) => {
  return new Date(ms).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
};

export const exportPDF = (session: SessionState | HistorySession, dateStr: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("TimeLog", pageWidth / 2, 20, { align: "center" });
  
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Daily Attendance Report", pageWidth / 2, 28, { align: "center" });

  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(20, 35, pageWidth - 20, 35);

  // Date & Time
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(10);
  doc.text(`Date: ${formatDate(new Date(session.checkInTime || Date.now()))}`, pageWidth - 20, 45, { align: 'right' });
  doc.text(`Export time: ${formatTimeShort(Date.now())}`, pageWidth - 20, 52, { align: 'right' });

  // Summary Box
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(20, 60, pageWidth - 40, 50, 3, 3, 'FD');
  
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 25, 68);
  
  doc.setFont("helvetica", "normal");
  const checkInStr = session.checkInTime ? formatTimeShort(session.checkInTime) : '-';
  const checkOutStr = session.checkOutTime ? formatTimeShort(session.checkOutTime) : '-';
  
  let totalSessionMs = 0;
  let totalBreakMs = 0;
  let effectiveMs = 0;
  let breakCount = session.breaks.length;

  if ('summary' in session) {
    totalSessionMs = session.summary.totalSession;
    totalBreakMs = session.summary.totalBreak;
    effectiveMs = session.summary.effectiveHours;
  } else {
    totalBreakMs = session.breaks.reduce((acc, b) => acc + ((b.end || Date.now()) - b.start), 0);
    totalSessionMs = session.checkInTime ? ((session.checkOutTime || Date.now()) - session.checkInTime) : 0;
    effectiveMs = Math.max(0, totalSessionMs - totalBreakMs);
  }

  doc.text(`Check-in: ${checkInStr}`, 25, 78);
  doc.text(`Check-out: ${checkOutStr}`, 25, 85);
  doc.text(`Total session: ${formatDuration(totalSessionMs)}`, 25, 92);
  
  doc.text(`Break time: ${formatDuration(totalBreakMs)}`, pageWidth / 2, 78);
  doc.text(`Effective hours: ${formatDuration(effectiveMs)}`, pageWidth / 2, 85);
  doc.text(`Number of breaks: ${breakCount}`, pageWidth / 2, 92);

  // Activity Log Table
  doc.setFont("helvetica", "bold");
  doc.text("Activity Log", 20, 125);
  
  doc.setFillColor(79, 70, 229);
  doc.setTextColor(255, 255, 255);
  doc.rect(20, 130, pageWidth - 40, 10, 'F');
  
  doc.setFontSize(10);
  doc.text("Time", 25, 137);
  doc.text("Event", 60, 137);
  doc.text("Duration", pageWidth - 45, 137);

  doc.setTextColor(17, 24, 39);
  doc.setFont("helvetica", "normal");
  
  let y = 147;
  session.logs.forEach((log, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(20, y - 6, pageWidth - 40, 10, 'F');
    }
    
    doc.text(formatTimeShort(log.time), 25, y);
    doc.text(log.event, 60, y);
    if (log.durationMs) {
      doc.text(formatDuration(log.durationMs), pageWidth - 45, y);
    }
    
    y += 10;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(229, 231, 235);
  doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);
  
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(8);
  doc.text("Generated by TimeLog · Personal Time Tracker", pageWidth / 2, pageHeight - 12, { align: "center" });

  doc.save(`TimeLog_${dateStr}.pdf`);
};

export const downloadJSON = (data: any, filename: string) => {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};
